---
- name: Destroy Phish Digital Ocean DNS
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    force_init: true
    state: "{{ state }}"
    targets:
      - digitalocean_record.gophish_hostname
      - digitalocean_record.gpadmin_hostname
      - digitalocean_record.gpredirect_hostname
      - digitalocean_domain.domain
    variables:
      do_token: "{{ digitalocean_token }}"
      gophish_hostname: "{{ gophish_site_hostname }}"
      gpadmin_hostname: "{{ gophish_admin_hostname }}"
      tl_domain: "{{ domain_name }}"
      do_img: "ubuntu-20-04-x64"
      do_name: "{{ user_tag }}-{{ op_number }}-phish"
      do_region: "{{ digitalocean_region }}"
      do_size: "{{ digitalocean_size }}"
      op: "{{ op_number }}"
      ttl: "{{ ttl }}"
      ansible_ssh_key: "{{ lookup('file', '{{ ansible_ssh_public_key_file }}') }}"
  tags: [ never, phish ]